version: '3.4'
services:
  verdaccio:
    container_name: verdaccio
    build:
      context: .
      dockerfile: Dockerfile.verdaccio
    ports:
      - "4873:4873"
    volumes:
      - verdaccio-volume:/verdaccio/storage
volumes:
  verdaccio-volume: